version: "2"
services:
  day:
    image: digit:1.0
    devices:
     - "/dev/gpiomem:/dev/gpiomem"
    restart: always
    entrypoint:
     - python
     - day.py
  clock:
    image: digit:1.0
    devices:
     - "/dev/gpiomem:/dev/gpiomem"
    restart: always
    entrypoint:
     - python
     - clock.py
  temperature:
    image: digit:1.0
    restart: always
    devices:
     - "/dev/gpiomem:/dev/gpiomem"
    entrypoint:
     - python
     - temperature.py
